<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
    <Platforms>x64;ARM64</Platforms>
    <PlatformTarget>$(Platform)</PlatformTarget>

    <AssemblyName>Community.PowerToys.Run.Plugin.BrowserConnect</AssemblyName>
    <RootNamespace>Community.PowerToys.Run.Plugin.BrowserConnect</RootNamespace>
    
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <Version>0.2.2</Version>
    <AssemblyVersion>0.2.2.0</AssemblyVersion>
    <FileVersion>0.2.2.0</FileVersion>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Community.PowerToys.Run.Plugin.BrowserConnect.Tests\**\*.cs" />
    <EmbeddedResource Remove="Community.PowerToys.Run.Plugin.BrowserConnect.Tests\**\*" />
    <None Remove="Community.PowerToys.Run.Plugin.BrowserConnect.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Community.PowerToys.Run.Plugin.Dependencies" Version="0.96.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Images\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
